'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CompteBancaire
    Public Property Id As Long
    Public Property UserId As String

    Public Property Code As String
    Public Property DatePeremption As DateTime? = Now
    Public Property Solde As Decimal?

    Public Property StatutExistant As Boolean?
    Public Property DateCreation As DateTime?

    Public Overridable Property User As ApplicationUser
End Class
