'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ConsulterCv
    Public Property UserId As String
    Public Property CvId As Long

    Public Property DateConsulter As DateTime = Now

    Public Overridable Property User As ApplicationUser
    Public Overridable Property cv As Cv

End Class
