'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Cursus
    Public Property Id As Long
    Public Property TypeCursusId As Long?
    Public Property CvId As Long?

    Public Property Titre As String
    Public Property Poste As String
    Public Property Structures As String
    Public Property Diplome As String
    Public Property Periode As String

    Public Property StatutExistant As Boolean?
    Public Property DateCreation As DateTime?

    Public Overridable Property TypeCursus As TypeCursus
    Public Overridable Property Cv As Cv

End Class
