'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Divers
    Public Property Id As Long
    Public Property CvId As Long?

    Public Property Titre As String
    Public Property Commentaire As String

    Public Property StatutExistant As Boolean?
    Public Property DateCreation As Date?

    Public Overridable Property cv As Cv
End Class
