'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Jobs
    Public Property Id As Long

    Public Property UserPublierId As String
    Public Overridable Property UserPublier As ApplicationUser

    Public Property UserAttribuerId As String
    Public Overridable Property UserAttribuer As ApplicationUser

    'Public Property UserPostulerId As String
    'Public Overridable Property UserPostuler As ApplicationUser

    Public Property TypeJobId As Long?
    Public Property SousSecteurActiviteId As Long?
    Public Property StatutId As Long?

    Public Property Titre As String
    Public Property Duree As String
    Public Property Code As String
    Public Property Description As String
    Public Property LieuExecution As String
    Public Property DatePrevueLivraison As DateTime = Now
    Public Property DatePublication As DateTime? = Now
    Public Property DateAttribution As DateTime? = Now
    Public Property DateCloture As DateTime? = Now
    Public Property BudgetMinimal As Decimal?
    Public Property BudgetMaximal As Decimal?
    Public Property BudgetAttribution As String
    Public Property CahierDeCharge As Byte()

    Public Property StatutExistant As Boolean?
    Public Property DateCreation As DateTime?

    Public Overridable Property TypeJob As TypeJob
    Public Overridable Property SousSecteurActivite As SousSecteurActivite
    Public Overridable Property statut As Statut


End Class
