'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PersonneDeReference
    Public Property Id As Long
    Public Property CvId As Long?

    Public Property Nom As String
    Public Property Prenom As String
    Public Property Sexe As String
    Public Property Telephone As String
    Public Property Profession As String
    Public Property Email As String

    Public Property StatutExistant As Boolean?
    Public Property DateCreation As DateTime?

    Public Overridable Property Cv As Cv
End Class
