'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PostulerJob
    Public Property UserId As String
    Public Property JobsId As Long

    Public Property Description As String
    Public Property DureeExecution As String
    Public Property BudgetExige As Decimal?
    Public Property DateEnvoi As DateTime = Now

    Public Property StatutExistant As Boolean?
    Public Property DateCreation As DateTime?

    Public Overridable Property User As ApplicationUser
    Public Overridable Property Job As Jobs
End Class
