'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Service
    Public Property Id As Long
    Public Property UserId As String
    Public Property SousSecteurActiviteId As Long?

    Public Property Titre As String
    Public Property Description As String
    Public Property DatePostulation As DateTime? = Now
    Public Property DureeRealisation As String
    Public Property MontantMinimal As Decimal?
    Public Property MontantMaximal As Decimal?

    Public Property StatutExistant As Boolean?
    Public Property DateCreation As DateTime?

    Public Overridable Property User As ApplicationUser
    Public Overridable Property SousSecteurActivite As SousSecteurActivite
End Class
