'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class SousSecteurActivite
    Public Property Id As Long
    Public Property SecteurActiviteId As Long?

    Public Property Libelle As String
    Public Property Description As String
    Public Property Code As String

    Public Property StatutExistant As Boolean?
    Public Property DateCreation As DateTime?

    Public Overridable Property SecteurActivite As SecteurActivite
    Public Overridable Property Service As ICollection(Of Service) = New HashSet(Of Service)
    Public Overridable Property Jobs As ICollection(Of Jobs) = New HashSet(Of Jobs)
    'Public Overridable Property User As ICollection(Of ApplicationUser) = New HashSet(Of ApplicationUser)
End Class
